# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    
- task: AzureSpringCloud@0
  inputs:
    azureSubscription: 'pool-01-196(d4cde383-3611-4557-b2b1-b64b50378c9d)'
    Action: 'Deploy'
    AzureSpringCloud: $(serviceName)
    AppName: 'account-service'
    UseStagingDeployment: true
    CreateNewDeployment: true
    DeploymentName: test-123
    
- task: AzureSpringCloud@0
  inputs:
    azureSubscription: 'pool-01-196(d4cde383-3611-4557-b2b1-b64b50378c9d)'
    Action: 'Set Production'
    AzureSpringCloud: $(serviceName)
    AppName: 'account-service'
    UseStagingDeployment: true
    DeploymentName: test-123